#!/usr/bin/env node
/**
 * Build script for @open-federation/lexicon package.
 *
 * 1. Validates all net.openfederation.* lexicon JSON files
 * 2. Copies them into packages/openfederation-lexicon/schemas/
 * 3. Generates src/index.ts barrel with schemas array, schemaMap, and nsids
 * 4. Generates src/types.ts with public TypeScript types from src/lexicon/generated.ts
 */

import fs from 'fs';
import path from 'path';
import { parseLexiconDoc, type LexiconDoc } from '@atproto/lexicon';

const LEXICON_SRC = path.resolve('src/lexicon');
const PKG_DIR = path.resolve('packages/openfederation-lexicon');
const SCHEMAS_DIR = path.join(PKG_DIR, 'schemas');
const BARREL_PATH = path.join(PKG_DIR, 'src', 'index.ts');
const TYPES_PATH = path.join(PKG_DIR, 'src', 'types.ts');
const GENERATED_PATH = path.resolve('src/lexicon/generated.ts');
const PREFIX = 'net.openfederation.';

async function main() {
  // 1. Find all net.openfederation.* JSON files
  const files = fs.readdirSync(LEXICON_SRC)
    .filter(f => f.startsWith(PREFIX) && f.endsWith('.json'))
    .sort();

  if (files.length === 0) {
    console.error('No net.openfederation.* lexicon files found in src/lexicon/');
    process.exit(1);
  }

  console.log(`Found ${files.length} lexicon schemas`);

  // 2. Validate each file. Collect all failures so a single run surfaces
  //    every invalid schema instead of bailing on the first one — makes
  //    batch-fixing tractable.
  const validated: Array<{ file: string; doc: LexiconDoc }> = [];
  const invalidFiles: Array<{ file: string; err: unknown }> = [];

  for (const file of files) {
    const filePath = path.join(LEXICON_SRC, file);
    const raw = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

    // Validate with @atproto/lexicon
    let doc: LexiconDoc;
    try {
      doc = parseLexiconDoc(raw);
    } catch (err) {
      invalidFiles.push({ file, err });
      console.error(`INVALID: ${file}`);
      continue;
    }

    // Verify filename matches id
    const expectedId = file.replace('.json', '');
    if (doc.id !== expectedId) {
      console.error(`ID MISMATCH: ${file}`);
      console.error(`  filename implies "${expectedId}" but id is "${doc.id}"`);
      process.exit(1);
    }

    validated.push({ file, doc });
    console.log(`  ✓ ${doc.id}`);
  }

  if (invalidFiles.length > 0) {
    console.error(`\n${invalidFiles.length} invalid schema(s):`);
    for (const { file } of invalidFiles) {
      console.error(`  - ${file}`);
    }
    process.exit(1);
  }

  // If --validate-only, stop after validation
  if (process.argv.includes('--validate-only')) {
    console.log(`\n✓ All ${validated.length} schemas valid`);
    return;
  }

  // 3. Copy JSON files to schemas/
  fs.mkdirSync(SCHEMAS_DIR, { recursive: true });

  // Clean existing schemas
  for (const existing of fs.readdirSync(SCHEMAS_DIR)) {
    fs.unlinkSync(path.join(SCHEMAS_DIR, existing));
  }

  for (const { file } of validated) {
    fs.copyFileSync(
      path.join(LEXICON_SRC, file),
      path.join(SCHEMAS_DIR, file),
    );
  }

  // 4. Generate barrel src/index.ts
  fs.mkdirSync(path.join(PKG_DIR, 'src'), { recursive: true });

  const imports: string[] = [];
  const schemaEntries: string[] = [];
  const mapEntries: string[] = [];
  const nsidEntries: string[] = [];

  for (let i = 0; i < validated.length; i++) {
    const { file, doc } = validated[i];
    const varName = `schema${i}`;
    const relPath = `../schemas/${file}`;

    imports.push(`import ${varName}Raw from '${relPath}';`);
    imports.push(`const ${varName} = ${varName}Raw as unknown as LexiconDoc;`);
    schemaEntries.push(`  ${varName},`);
    mapEntries.push(`  '${doc.id}': ${varName},`);

    // Convert NSID to PascalCase key: net.openfederation.community.get -> CommunityGet
    const shortId = doc.id.replace('net.openfederation.', '');
    const camelKey = shortId
      .split('.')
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');
    nsidEntries.push(`  ${camelKey}: '${doc.id}' as const,`);
  }

  const barrel = `// AUTO-GENERATED by scripts/build-lexicon-package.ts — do not edit
import type { LexiconDoc } from '@atproto/lexicon';

${imports.join('\n')}

/** All OpenFederation lexicon schemas as an array. */
export const schemas: LexiconDoc[] = [
${schemaEntries.join('\n')}
];

/** Lexicon schemas keyed by NSID for direct lookup. */
export const schemaMap: Record<string, LexiconDoc> = {
${mapEntries.join('\n')}
};

/** All OpenFederation NSIDs as typed constants. */
export const nsids = {
${nsidEntries.join('\n')}
} as const;

export type { LexiconDoc } from '@atproto/lexicon';

// TypeScript input/output types derived from lexicon schemas (for BFF consumers).
export type * from './types.js';
`;

  fs.writeFileSync(BARREL_PATH, barrel);

  // 5. Generate src/types.ts from the generated contracts file.
  //    Include all named types but strip the PDS-internal LexiconInputMap /
  //    LexiconOutputMap / LexiconErrorMap / LexiconRevisionMap declarations.
  if (!fs.existsSync(GENERATED_PATH)) {
    console.error(`\nERROR: ${GENERATED_PATH} not found. Run npm run lexicon:generate first.`);
    process.exit(1);
  }
  const generatedSrc = fs.readFileSync(GENERATED_PATH, 'utf-8');
  const mapBoundary = generatedSrc.indexOf('\nexport interface LexiconInputMap {');
  const publicTypes = mapBoundary > -1 ? generatedSrc.slice(0, mapBoundary).trimEnd() : generatedSrc;
  const typesFile = `// AUTO-GENERATED by scripts/build-lexicon-package.ts — do not edit
// Public TypeScript types derived from net.openfederation.* lexicon schemas.
// Import as: import type { NetOpenfederationContactListOutput } from '@open-federation/lexicon';

${publicTypes.replace(/^\/\/ AUTO-GENERATED[^\n]*\n/, '')}\n`;
  fs.writeFileSync(TYPES_PATH, typesFile);

  console.log(`\n✓ Copied ${validated.length} schemas to ${SCHEMAS_DIR}`);
  console.log(`✓ Generated barrel at ${BARREL_PATH}`);
  console.log(`✓ Generated types at ${TYPES_PATH}`);
}

main();
