#!/usr/bin/env node
/**
 * Generate server-side TypeScript contracts from src/lexicon/*.json.
 */

import fs from 'fs';
import path from 'path';

type Schema = {
  type?: string;
  ref?: string;
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
};

type LexiconDoc = {
  id: string;
  revision?: number;
  defs?: {
    main?: {
      type?: string;
      input?: { schema?: Schema };
      parameters?: Schema;
      output?: { schema?: Schema };
      errors?: Array<{ name?: string }>;
    };
    [key: string]: unknown;
  };
};

const LEXICON_DIR = path.resolve('src/lexicon');
const OUTPUT_PATH = path.resolve('src/lexicon/generated.ts');

function main(): void {
  const docs = fs.readdirSync(LEXICON_DIR)
    .filter((file) => file.endsWith('.json'))
    .sort()
    .map((file) => JSON.parse(fs.readFileSync(path.join(LEXICON_DIR, file), 'utf-8')) as LexiconDoc)
    .sort((a, b) => a.id.localeCompare(b.id));

  const output = renderContracts(docs);

  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf-8') : '';
    if (current !== output) {
      console.error('Generated lexicon contracts are stale. Run npm run lexicon:generate.');
      process.exit(1);
    }
    console.log('Generated lexicon contracts are up to date.');
    return;
  }

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`Generated ${OUTPUT_PATH}`);
}

function renderContracts(docs: LexiconDoc[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/generate-lexicon-contracts.ts - do not edit',
    '',
    'export type JsonObject = { [key: string]: unknown };',
    '',
  ];

  const contractEntries: string[] = [];
  const inputEntries: string[] = [];
  const outputEntries: string[] = [];
  const errorEntries: string[] = [];

  for (const doc of docs) {
    const typeName = toTypeName(doc.id);
    const main = doc.defs?.main;
    const inputSchema = main?.type === 'query' ? main.parameters : main?.input?.schema;
    const outputSchema = main?.output?.schema;
    const errors = (main?.errors ?? [])
      .map((error) => error.name)
      .filter((name): name is string => typeof name === 'string' && name.length > 0)
      .sort();

    lines.push(`export type ${typeName}Input = ${schemaToType(doc, inputSchema)};`);
    lines.push(`export type ${typeName}Output = ${schemaToType(doc, outputSchema)};`);
    lines.push(`export type ${typeName}Error = ${unionOfStrings(errors)};`);
    lines.push('');

    contractEntries.push(`  '${doc.id}': { revision: ${Number(doc.revision) || 1}, errors: ${arrayOfStrings(errors)} },`);
    inputEntries.push(`  '${doc.id}': ${typeName}Input;`);
    outputEntries.push(`  '${doc.id}': ${typeName}Output;`);
    errorEntries.push(`  '${doc.id}': ${typeName}Error;`);
  }

  lines.push('export interface LexiconInputMap {');
  lines.push(...inputEntries);
  lines.push('}');
  lines.push('');
  lines.push('export interface LexiconOutputMap {');
  lines.push(...outputEntries);
  lines.push('}');
  lines.push('');
  lines.push('export interface LexiconErrorMap {');
  lines.push(...errorEntries);
  lines.push('}');
  lines.push('');
  lines.push('export type LexiconNsid = keyof LexiconInputMap;');
  lines.push('');
  lines.push('export const lexiconContracts = {');
  lines.push(...contractEntries);
  lines.push('} as const;');
  lines.push('');

  return `${lines.join('\n').replace(/\n+$/u, '')}\n`;
}

function schemaToType(doc: LexiconDoc, schema: Schema | undefined): string {
  if (!schema) return 'undefined';
  if (schema.type === 'ref') {
    return schemaToType(doc, resolveRef(doc, schema.ref));
  }
  if (schema.type === 'unknown') return 'unknown';
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'array') return `Array<${schemaToType(doc, schema.items)}>`;
  if (schema.type === 'object' || schema.type === 'params') {
    const properties = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const fields = Object.entries(properties).map(([name, child]) => {
      const optional = required.has(name) ? '' : '?';
      return `  ${JSON.stringify(name)}${optional}: ${schemaToType(doc, child)};`;
    });
    if (fields.length === 0) return 'JsonObject';
    return `{\n${fields.join('\n')}\n}`;
  }
  return 'unknown';
}

function resolveRef(doc: LexiconDoc, ref: string | undefined): Schema | undefined {
  if (!ref?.startsWith('#')) return undefined;
  const def = doc.defs?.[ref.slice(1)];
  return isSchema(def) ? def : undefined;
}

function isSchema(value: unknown): value is Schema {
  return typeof value === 'object' && value !== null && ('type' in value || 'ref' in value);
}

function toTypeName(nsid: string): string {
  return nsid
    .split('.')
    .map((part) => part.replace(/(^|[-_])([a-zA-Z0-9])/g, (_m, _sep, c: string) => c.toUpperCase()))
    .join('');
}

function unionOfStrings(values: string[]): string {
  return values.length > 0 ? values.map((value) => JSON.stringify(value)).join(' | ') : 'never';
}

function arrayOfStrings(values: string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}] as const`;
}

main();
